# Generated by Django 4.0.5 on 2022-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_expiring_time_alter_imagesizes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiring_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
