# Generated by Django 4.0.5 on 2022-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_expiring_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_expiring',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
