# Generated by Django 4.0.5 on 2022-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_image_expiring_time_alter_image_image_expiring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiring_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
