# Generated by Django 4.0.5 on 2022-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_image_expiring_time_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesizes',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
