# Generated by Django 4.0.5 on 2022-06-14 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_imagesizes_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesizes',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
