# Generated by Django 4.0.5 on 2022-06-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='expiring_links',
            new_name='expiring_link',
        ),
    ]
